import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import dynamic from "next/dynamic";
import Footer from "./Footer";

const inter = Inter({ subsets: ["latin"] });

const DynamicHeaderWithNoSSR = dynamic(() => import("./Header"), {
  ssr: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <DynamicHeaderWithNoSSR />
        {children}
        <Footer />
      </body>
    </html>
  );
}
