import type { Metadata } from "next";
import dynamic from "next/dynamic";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

const DynamicHeaderWithNoSSR = dynamic(
  () => import("./Header"), // replace './Header' with the path to your Header component
  { ssr: false },
);

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className={`flex min-h-screen flex-col ${inter.className}`}>
          <DynamicHeaderWithNoSSR />
          <main className="flex-grow">{children}</main>
        </div>
      </body>
    </html>
  );
}
